version: "3"
services:
  database:
    container_name: socialmedia-data
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27019:27017"
    networks:
      - mongodb_network

  social-backend:
    container_name: socialmedia-data-backend
    image: node:14
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - "$PWD:/app"
    working_dir: "/app"
    command: ["npm", "run", "dev"]

    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_PORT=27019
      - DATABASE_NAME=socialmedia-data
      - PORT=3000
    
    ports:
      - "3000:3000"
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge